const buildHelper = require("@egjs/build-helper");

const external = {
  "@egjs/axes": "eg.Axes",
  "@egjs/component": "eg.Component",
  "@egjs/agent": "eg.agent",
  "gl-matrix": "glMatrix",
  "webvr-polyfill": "WebVRPolyfill",
}
const name = "eg.view360";

export default buildHelper([
  {
    name,
    input: "./src/index.umd.ts",
    output: "./dist/view360.js",
    format: "umd",
    commonjs: true,
    external,
  },
  {
    name,
    input: "./src/PanoViewer/index.umd.ts",
    output: "./dist/view360.panoviewer.js",
    format: "umd",
    commonjs: true,
    external,
  },
  {
    name,
    input: "./src/SpinViewer/index.umd.ts",
    output: "./dist/view360.spinviewer.js",
    format: "umd",
    commonjs: true,
    external,
  },
  {
    name,
    input: "./src/index.umd.ts",
    output: "./dist/view360.min.js",
    format: "umd",
    commonjs: true,
    uglify: true,
    external,
  },
  {
    name,
    input: "./src/PanoViewer/index.umd.ts",
    output: "./dist/view360.panoviewer.min.js",
    format: "umd",
    commonjs: true,
    uglify: true,
    external,
  },
  {
    name,
    input: "./src/SpinViewer/index.umd.ts",
    output: "./dist/view360.spinviewer.min.js",
    format: "umd",
    commonjs: true,
    uglify: true,
    external,
  },
  {
    name,
    input: "./src/index.umd.ts",
    output: "./dist/view360.pkgd.js",
    format: "umd",
    commonjs: true,
    resolve: true,
  },
  {
    name,
    input: "./src/PanoViewer/index.umd.ts",
    output: "./dist/view360.panoviewer.pkgd.js",
    format: "umd",
    commonjs: true,
    resolve: true,
  },
  {
    name,
    input: "./src/SpinViewer/index.umd.ts",
    output: "./dist/view360.spinviewer.pkgd.js",
    format: "umd",
    commonjs: true,
    resolve: true,
  },
  {
    name,
    input: "./src/index.umd.ts",
    output: "./dist/view360.pkgd.min.js",
    format: "umd",
    commonjs: true,
    resolve: true,
    uglify: true,
  },
  {
    name,
    input: "./src/PanoViewer/index.umd.ts",
    output: "./dist/view360.panoviewer.pkgd.min.js",
    format: "umd",
    commonjs: true,
    resolve: true,
    uglify: true,
  },
  {
    name,
    input: "./src/SpinViewer/index.umd.ts",
    output: "./dist/view360.spinviewer.pkgd.min.js",
    format: "umd",
    commonjs: true,
    resolve: true,
    uglify: true,
  },
  {
    input: "./src/index.ts",
    output: "./dist/view360.esm.js",
    format: "esm",
    exports: "named",
    commonjs: true,
    external,
  },
]);

