module.exports = {
  docs: [
    {
      type: "autogenerated",
      dirName: "tutorials"
    }
  ],
  api: [{ type: "autogenerated", dirName: "api" }],
  options: [
    {
      type: "category",
      label: "PanoViewer",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Source",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: "autogenerated",
              dirName: "options/PanoViewer/source"
            }
          ]
        }
      ]
    },
    {
      type: "category",
      label: "SpinViewer",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Source",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: "autogenerated",
              dirName: "options/SpinViewer/source"
            }
          ]
        }
      ]
    }
  ],
  events: [
    {
      type: "autogenerated",
      dirName: "events"
    }
  ]
};
