module.exports = {
  docs: [
    {
      type: "autogenerated",
      dirName: "tutorials"
    }
  ],
  options: [
    {
      type: "category",
      label: "Source",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "options/source"
        }
      ]
    }
  ],
  events: [
    {
      type: "autogenerated",
      dirName: "events"
    }
  ],
  ...require("./sidebars-api.js")
};
