module.exports = {
  docs: [
    {
      type: "autogenerated",
      dirName: "tutorials"
    }
  ],
  api: [{ type: "autogenerated", dirName: "api" }],
  projections: [{ type: "autogenerated", dirName: "projections" }],
  options: [
    {
      type: "doc",
      id: "options/options-basics"
    },
    {
      type: "category",
      label: "Source",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "options/source"
        }
      ]
    },
    {
      type: "category",
      label: "Camera",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "options/camera"
        }
      ]
    },
    {
      type: "category",
      label: "Control",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "options/control"
        }
      ]
    },
    {
      type: "category",
      label: "Hotspot",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "options/hotspot"
        }
      ]
    },
    {
      type: "category",
      label: "Miscellaneous",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "options/miscellaneous"
        }
      ]
    }
  ],
  events: [
    {
      type: "autogenerated",
      dirName: "events"
    }
  ],
  plugins: [
    {
      type: "autogenerated",
      dirName: "plugins"
    }
  ]
};
